### PR TITLE
Add terraform config

### PR DESCRIPTION
**Pull request by roshan-parabol**
Terraform confg for rethinkdb instance, optional load balancer,GCS bucket, IAM and Service account

## Initial Setup:

To test, you need to install terraform CLI and gcloudCLI

- [Install terraform locally](https://developer.hashicorp.com/terraform/tutorials/aws-get-started/install-cli)

- Install[gcloud cli](https://cloud.google.com/sdk/docs/install) to connect with the GCP project locally so you can run terraform commands

- Run `gcloud init` and login to GCP and select the project

- Run `gcloud auth application-default login` to use your credentials for terraform

### CODE REVIEW

**Comment by roshan-parabol** [comment]
Output for terraform plan

```
➜  Terraform git:(main) ✗ terraform plan
google_compute_instance.default: Refreshing state... [id=projects/parabol-bp-roshan-rathod/zones/us-central1-a/instances/my-instance]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # google_compute_backend_service.rethinkdb_backend_service[0] will be created
  + resource "google_compute_backend_service" "rethinkdb_backend_service" {
      + connection_draining_timeout_sec = 300
      + creation_timestamp              = (known after apply)
      + enable_cdn                      = false
      + fingerprint                     = (known after apply)
      + generated_id                    = (known after apply)
      + id                              = (known after apply)
      + load_balancing_scheme           = "EXTERNAL"
      + name                            = "rethinkdb-backend-service"
      + port_name                       = "rethinkdb"
      + project                         = "parabol-bp-roshan-rathod"
      + protocol                        = "TCP"
      + self_link                       = (known after apply)
      + session_affinity                = (known after apply)
      + timeout_sec                     = 10

      + backend {
          + balancing_mode               = "UTILIZATION"
          + capacity_scaler              = 1
          + group                        = (known after apply)
          + max_connections              = (known after apply)
          + max_connections_per_endpoint = (known after apply)
          + max_connections_per_instance = (known after apply)
          + max_rate                     = (known after apply)
          + max_rate_per_endpoint        = (known after apply)
          + max_rate_per_instance        = (known after apply)
          + max_utilization              = (known after apply)
        }
    }

  # google_compute_forwarding_rule.rethinkdb_forwarding_rule[0] will be created
  + resource "google_compute_forwarding_rule" "rethinkdb_forwarding_rule" {
      + base_forwarding_rule  = (known after apply)
      + creation_timestamp    = (known after apply)
      + id                    = (known after apply)
      + ip_address            = (known after apply)
      + ip_protocol           = (known after apply)
      + label_fingerprint     = (known after apply)
      + load_balancing_scheme = "EXTERNAL"
      + name                  = "rethinkdb-forwarding-rule"
      + network               = (known after apply)
      + network_tier          = (known after apply)
      + port_range            = "8080"
      + project               = "parabol-bp-roshan-rathod"
      + psc_connection_id     = (known after apply)
      + psc_connection_status = (known after apply)
      + region                = "us-central1"
      + self_link             = (known after apply)
      + service_name          = (known after apply)
      + subnetwork            = (known after apply)
      + target                = (known after apply)
    }

  # google_compute_health_check.rethinkdb_health_check[0] will be created
  + resource "google_compute_health_check" "rethinkdb_health_check" {
      + check_interval_sec  = 5
      + creation_timestamp  = (known after apply)
      + healthy_threshold   = 2
      + id                  = (known after apply)
      + name                = "rethinkdb-health-check"
      + project             = (known after apply)
      + self_link           = (known after apply)
      + timeout_sec         = 5
      + type                = (known after apply)
      + unhealthy_threshold = 2

      + tcp_health_check {
          + port         = 8080
          + proxy_header = "NONE"
        }
    }

  # google_compute_instance.rethinkdb_instance will be created
  + resource "google_compute_instance" "rethinkdb_instance" {
      + can_ip_forward       = false
      + cpu_platform         = (known after apply)
      + current_status       = (known after apply)
      + deletion_protection  = false
      + guest_accelerator    = (known after apply)
      + id                   = (known after apply)
      + instance_id          = (known after apply)
      + label_fingerprint    = (known after apply)
      + machine_type         = "n1-standard-2"
      + metadata_fingerprint = (known after apply)
      + min_cpu_platform     = (known after apply)
      + name                 = "rethinkdb-vm"
      + project              = "parabol-bp-roshan-rathod"
      + self_link            = (known after apply)
      + tags_fingerprint     = (known after apply)
      + zone                 = "us-central1-b"

      + boot_disk {
          + auto_delete                = true
          + device_name                = (known after apply)
          + disk_encryption_key_sha256 = (known after apply)
          + kms_key_self_link          = (known after apply)
          + mode                       = "READ_WRITE"
          + source                     = (known after apply)

          + initialize_params {
              + image  = (known after apply)
              + labels = (known after apply)
              + size   = 10
              + type   = (known after apply)
            }
        }

      + network_interface {
          + ipv6_access_type   = (known after apply)
          + name               = (known after apply)
          + network            = "default"
          + network_ip         = (known after apply)
          + stack_type         = (known after apply)
          + subnetwork         = (known after apply)
          + subnetwork_project = (known after apply)
        }
    }

  # google_compute_target_pool.rethinkdb_target_pool[0] will be created
  + resource "google_compute_target_pool" "rethinkdb_target_pool" {
      + health_checks    = (known after apply)
      + id               = (known after apply)
      + instances        = (known after apply)
      + name             = "rethinkdb-target-pool"
      + project          = "parabol-bp-roshan-rathod"
      + region           = "us-central1"
      + self_link        = (known after apply)
      + session_affinity = "NONE"
    }

  # google_project_iam_member.rethinkdb_service_account_permissions will be created
  + resource "google_project_iam_member" "rethinkdb_service_account_permissions" {
      + etag    = (known after apply)
      + id      = (known after apply)
      + member  = (known after apply)
      + project = "parabol-bp-roshan-rathod"
      + role    = "roles/storage.objectAdmin"
    }

  # google_service_account.rethinkdb_service_account will be created
  + resource "google_service_account" "rethinkdb_service_account" {
      + account_id   = "rethinkdb-admin"
      + disabled     = false
      + display_name = "RethinkDB Service Account"
      + email        = (known after apply)
      + id           = (known after apply)
      + member       = (known after apply)
      + name         = (known after apply)
      + project      = "parabol-bp-roshan-rathod"
      + unique_id    = (known after apply)
    }

  # google_storage_bucket.rethinkdb_backup_bucket will be created
  + resource "google_storage_bucket" "rethinkdb_backup_bucket" {
      + force_destroy               = false
      + id                          = (known after apply)
      + location                    = "US-CENTRAL1"
      + name                        = "rethinkdb-backups"
      + project                     = "parabol-bp-roshan-rathod"
      + public_access_prevention    = (known after apply)
      + self_link                   = (known after apply)
      + storage_class               = "STANDARD"
      + uniform_bucket_level_access = true
      + url                         = (known after apply)
    }

Plan: 8 to add, 0 to change, 0 to destroy.
```

**Comment by roshan-parabol** [comment]
Ran into an error while applying changes. Looking into the error related to disk.


```
google_service_account.rethinkdb_service_account: Creating...
google_storage_bucket.rethinkdb_backup_bucket: Creating...
google_compute_health_check.rethinkdb_health_check[0]: Creating...
google_compute_instance.rethinkdb_instance: Creating...
google_service_account.rethinkdb_service_account: Creation complete after 2s [id=projects/parabol-bp-roshan-rathod/serviceAccounts/rethinkdb-admin@parabol-bp-roshan-rathod.iam.gserviceaccount.com]
google_project_iam_member.rethinkdb_service_account_permissions: Creating...
google_storage_bucket.rethinkdb_backup_bucket: Creation complete after 2s [id=rethinkdb-backups]
google_project_iam_member.rethinkdb_service_account_permissions: Creation complete after 7s [id=parabol-bp-roshan-rathod/roles/storage.objectAdmin/serviceAccount:rethinkdb-admin@parabol-bp-roshan-rathod.iam.gserviceaccount.com]
google_compute_health_check.rethinkdb_health_check[0]: Still creating... [10s elapsed]
google_compute_health_check.rethinkdb_health_check[0]: Creation complete after 12s [id=projects/parabol-bp-roshan-rathod/global/healthChecks/rethinkdb-health-check]
╷
│ Error: Error creating instance: googleapi: Error 400: Invalid value for field 'resource.disks[0]': '{  "mode": "READ_WRITE",  "boot": true,  "initializeParams": {    "diskSizeGb": "10"  },  "autoDelet...'. Boot disk must have a source specified., invalid
│
│   with google_compute_instance.rethinkdb_instance,
│   on main.tf line 7, in resource "google_compute_instance" "rethinkdb_instance":
│    7: resource "google_compute_instance" "rethinkdb_instance" {
│
╵
```

**Comment by roshan-parabol** [comment]
Got this working but removed the load balancer logic for now. Need to figure some things out there.

Currently, got a VM instance with attached storage, GCS bucket and Service Account.

**Comment by rafaelromcar-parabol** [comment]
Great job! 

Regarding disk type, SSD is the way to go for sure. About size, I would just put a variable there to allow choosing the size at creation time, but keep in mind that we can increase it afterwards ([doc](https://cloud.google.com/compute/docs/disks/resize-persistent-disk)).

The Load Balancer is less important than having a static private IP assigned to the instance. And Ansible is also way more important than the Load Balancer. Just saying, so you can concentrate on what's more important for now.

**Pull request merged**
